blank_issues_enabled: false
# contact_links:
#   - name: ğŸ™ Q&A
#     url: https://github.com/SaboZhang/Organize
#     about: Ask the community for help
#   - name: ğŸ’¡ Feature requests and ideas
#     url: https://github.com/SaboZhang/Organize
#     about: Share ideas for new features
#   - name: ğŸ™Œ Show and tell
#     url: https://github.com/SaboZhang/Organize
#     about: Show off something you've made
